services:
  # Backend Node.js Service
  - type: web
    name: resume-ai-backend
    runtime: node
    plan: starter
    region: singapore
    branch: main
    
    # Correct build command to install, migrate, and build
    buildCommand: "npm install && npx prisma migrate deploy && npm run build"
    
    # Command to start the server
    startCommand: "npm start"
    
    # Health check endpoint for Render to monitor service health
    healthCheckPath: /health
    
    envVars:
      # Non-sensitive environment variables
      - key: NODE_ENV
        value: production
      - key: JWT_EXPIRES_IN
        value: 7d
        
      # Reference to your frontend URL
      - key: FRONTEND_URL
        value: https://resume-ai-ri2r.onrender.com
        
      # Secrets - These must be set in the Render Dashboard
      # Go to Environment -> Secret Files -> Add Secret File
      # Or add them as individual environment variables
      - key: DATABASE_URL
        fromSecret: true
      - key: OPENAI_API_KEY
        fromSecret: true
      - key: ELEVENLABS_API_KEY
        fromSecret: true
      - key: JWT_SECRET
        fromSecret: true

